language: objective-c
env:
 global:
   - "ARTIFACTS_AWS_REGION=us-east-1"
   - "ARTIFACTS_S3_BUCKET=builds.appcelerator.com"
   - secure: "LFp2aVjUEghOLAvcTZMfAvrM9KUcmquOH8Sq9fuvTPBTpyopEpec1WNwV0oGL+j6xCXgxiBNNfOZ17AJyq8weKZC3wWaLQk6m9KbIfzL0ZgGz3jil+V1KijVrLkb6sMM0K4DCHIA6gLMqU6xg330tmwWWfHAPDrjjs+yV5v29GU="
   - secure: "nvH44W01netO1voX5EbzRjz3Rvv97e6j5GeprxwroEwEF28a15sNW9keCL7/uYW1bkCgZyNeRF9DiG2N3VBy79YxsA8katM4FsuVdxM1BgZtvuNJ4foUdXZwfPoFy3Y1jvc1IYup75aBC7tj/IV4jMfnPWB31niPWmANN0nY4Zw="
   - "MODULE_NAME=ti.styledlabel"
before_install:
    - MODULE_ROOT=$PWD
    - "gem install travis-artifacts"
install:
    - cd $MODULE_ROOT
    - curl -o install.sh https://raw.githubusercontent.com/appcelerator-modules/ci/master/travis/install.sh
    - source install.sh
    
before_script:
    - cd $MODULE_ROOT
script: 
    - if [ -d "$MODULE_ROOT/ios/" ]; then
    -   cd $MODULE_ROOT/ios/
    -   ./build.py
    - fi

    - if [ -d "$MODULE_ROOT/android/" ]; then
    -   cd $MODULE_ROOT/android/
    -   cp $MODULE_ROOT/build.properties build.properties
    -   ant clean
    -   ant
    - fi
after_failure: # this will of course run only on failure
  - "travis-artifacts upload --path debug/debug.log"
after_success: # and this only on success
  - curl -o deploy.sh https://raw.githubusercontent.com/appcelerator-modules/ci/master/travis/deploy.sh
  - source deploy.sh
